# This Dockerfile is only used to build the base image for the project in order to avoid
# Unnecessarily long build times.
# It is a Debian-based Python3 image.
# It contains all the necessary python packages to run the CLAMOUR project.

FROM balenalib/raspberry-pi-debian-python:3.7.2

# Some base python packages must be installed through 
# apt-get because installing them with pip fails.
RUN apt-get update && apt-get install python3-numpy python3-scipy python3-matplotlib

# Some base packages are needed just to install pygame
RUN apt-get install build-essential python3-dev python3-setuptools python3-numpy python3-opengl \
    libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev \
    libsdl1.2-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
    libtiff5-dev libx11-6 libx11-dev fluid-soundfont-gm timgm6mb-soundfont \
    xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic fontconfig fonts-freefont-ttf libfreetype6-dev

COPY requirements.txt /
RUN pip install --upgrade pip setuptools && \
    pip install --no-cache-dir -r requirements.txt
