from enum import Enum


class State(Enum):
    INITIALIZATION = 0
    SYNCHRONIZATION = 1
    SCHEDULING = 2
    TASK = 3
    LISTEN = 4


JUMP_THRESHOLD = 3.0
GRAVITATIONAL_ACCELERATION = 9.81
TAG_ID_MASK = 0xFF

NB_SAMPLES_OFFSET = 10
TRANSMISSION_SCALING = 100000
RANDOM_DELAY_MEAN = 0.001  # ms
RANDOM_DELAY_VARIANCE = 0.05  # ms
