from enum import Enum


class State(Enum):
    INITIALIZATION = 0
    SYNCHRONIZATION = 1
    SCHEDULING = 2
    TASK = 3
    LISTEN = 4


JUMP_THRESHOLD = 0.5
GRAVITATIONAL_ACCELERATION = 9.81
TAG_ID_MASK = 0xFF
