from enum import Enum


class State(Enum):
    INITIALIZATION = 0
    SYNCHRONIZATION = 1
    SCHEDULING = 2
    TASK = 3
    LISTEN = 4


JUMP_THRESHOLD = 3000
GRAVITATIONAL_ACCELERATION = 9.81
SECONDS_TO_MILLISECONDS = 1000
TAG_ID_MASK = 0xFF

NB_SAMPLES_OFFSET = 20
TRANSMISSION_SCALING = 100
RANDOM_DELAY_MEAN = 0.001  # ms
RANDOM_DELAY_VARIANCE = 0.05  # ms
