tag_type: Bitcraze # Manufacturer of the tag. Bitcraze or Pozyx
tag_id: 11         # Tag IDs must be >10. Pozyx does not currently support ID assignement through config file. 

dw1000_bus: 0      # If using a Bitcraze Tag, this specifies the SPI bus where it's connected 
dw1000_cs:  0      # If using a Bitcraze Tag, this specifies the chip select # where it's connected 